# Generated by Django 4.2.11 on 2025-04-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='categories',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Depth in inches/cm', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='has_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='medium',
            field=models.CharField(choices=[('3D', '3D template'), ('oil', 'Oil on Canvas'), ('acrylic', 'Acrylic'), ('watercolor', 'Watercolor'), ('digital', 'Digital Art'), ('photography', 'Photography'), ('mixed', 'Mixed Media'), ('sculpture', 'Sculpture'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
