# Generated by Django 4.2.11 on 2025-04-30 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_artist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
