# Generated by Django 4.2.11 on 2025-04-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_delete_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
